config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'customer_details/new/:id', to: 'customer_details#new', as: 'new_customer_details'
  get 'customer_details/:id/download', to: 'customer_details#download', as: 'download'
  get 'homes/hello'
  get 'homes/cpm'
  root to: 'homes#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'slots/new/:id', to: 'slots#new', as: 'new_slot'
  
  resources :slots do
    collection do
      get 'booked_slot', to: 'slots#booked_slot'
      get 'empty_slot', to: 'slots#empty_slot'
    end

    # member do
    #   get 'new/:id', to: 'slots#new', as: 'new_slot'
    # end
  end

  resources :customer_details, except: %i[new]

  resources :floors do
  end
  get 'floors/booked_floor/:id' => 'floors#booked_floor', as: 'booked_floor_slots'
  get 'floors/empty_floor/:id' => 'floors#empty_floor', as: 'empty_floor_slots'

end

app/views/shaerd/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark  text-white bg-dark" >
  <div class="container">
    <a class="navbar-brand mr-5" href="http://localhost:3000/homes/cpm"> CPM </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ">
        <% if user_signed_in? %>

          <li class="nav-item active">
            <%= link_to "Home" ,root_path , class: "nav-link mr-4"%>
          </li>

           <li class="nav-item active">
            <%= link_to 'Apply Here', floors_path , class: "nav-link mr-4"%>
          </li>

          <% if !current_user.admin %>
            <li class="nav-item active">
              <%= link_to 'Your Booking', customer_details_path, class: "nav-link mr-4"%>
            </li>
          <%else%>
            <li class="nav-item active">
              <%= link_to 'All Booking', customer_details_path , class: "nav-link mr-4"%>
            </li>
            <li class="nav-item active">
              <%= link_to "Slot" ,slots_path , class: "nav-link mr-4"%>
            </li>
          <%end%>  

          <li class="nav-item active">
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link mr-4' %> 
          </li>

          <li class="nav-item m-auto active ">
            <%=  link_to "Logout", destroy_user_session_path,  data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } , class: "nav-link mr-5" %>
          </li>

          <% else %>

          <li class="nav-item active">
            <%=  link_to "Sign up", new_user_registration_path , class: "nav-link"%>
          </li>

          <li class="nav-item active">
            <%=  link_to "Login", new_user_session_path , class: "nav-link"%>
          </li>
          
        <%end%>
        
      </ul>
    </div>
  </div>
</nav>