config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'customer_details/new/:id', to: 'customer_details#new', as: 'new_customer_details'
  get 'customer_details/:id/download', to: 'customer_details#download', as: 'download'
  get 'homes/hello'
  get 'homes/cpm'
  root to: 'homes#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'slots/new/:id', to: 'slots#new', as: 'new_slot'
  
  resources :slots do
    collection do
      get 'booked_slot', to: 'slots#booked_slot'
      get 'empty_slot', to: 'slots#empty_slot'
    end

    # member do
    #   get 'new/:id', to: 'slots#new', as: 'new_slot'
    # end
  end

  resources :customer_details, except: %i[new]

  resources :floors do
  end
  get 'floors/booked_floor/:id' => 'floors#booked_floor', as: 'booked_floor_slots'
  get 'floors/empty_floor/:id' => 'floors#empty_floor', as: 'empty_floor_slots'

end

app/models/slot.rb
# frozen_string_literal: true

class Slot < ApplicationRecord
  belongs_to :floor
  has_one :customer_detail
  validates :slot_number, presence: true

  scope :booked, -> { where(status: Slot::STATUS[:booked]) }
  scope :empty, -> { where(status: Slot::STATUS[:empty]) }

  STATUS = {
    booked: true,
    empty: false
  }

end

app/controllers/slots_controller.rb
# frozen_string_literal: true

class SlotsController < ApplicationController
  before_action :check_user, only: %i[destroy edit new]
  before_action :set_slot, only: %i[edit update show destroy]

  def new
    @slot = Slot.new
  end

  def index
    @slot = Slot.all
  end

  def show; end

  def edit; end

  def update
    result = Slots::UpdateSlotService.new(@slot, slot_params).call
    if result[:success]
      flash[:notice] = 'Slot Successfully Updated'
      redirect_to @slot
    else
      flash[:alert] = result[:errors].full_messages.join(', ')
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    result = Slots::CreateSlotService.new(slot_params).call
    if result[:success]
      flash[:notice] = 'Slot Successfully Created.'
      redirect_to result[:floor]
    else
      flash[:alert] = result[:errors].full_messages.join(', ')
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    if @slot.destroy
      flash[:notice] = 'Slot Successfully Deleted'
    else
      flash[:alert] = 'Failed to Delete Slot'
    end
    redirect_to slots_path
  end

  private

  def slot_params
    params.require(:slot).permit(:slot_number, :floor_id, :status)
  end

  def set_slot
    @slot = Slot.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:alert] = 'Slot not found'
    redirect_to slots_path
  end
end

app/helpers/slots_helper.rb
# frozen_string_literal: true

module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_with scope: :slot, url: slots_path, local: true do |f| %>

  <% if @slot.errors.any? %>
    <h2>The following errors prevented the SLOT from being saved</h2>
    <ul>
      <% @slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %> 

  <p> 
    <%= f.label :slot_number, class: 'mb-2'   %><br/>
    <%= f.number_field :slot_number, Placeholder: "Enter Slot Number", class: "form-control form-control-lg" %>
  </p>
  <p> 
    <%= f.hidden_field :floor_id, value: params[:id], class: "form-control form-control-lg" %>
  </p> 

  <p>
    <%= f.submit 'submit', class: "btn btn-primary" %> 
  </p>
<% end %>

app/views/slots/_show_slots.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <%= link_to 'All', slots_path, class: "btn btn-primary m-1" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Booked', booked_slot_slots_path, class: "btn btn-primary m-1" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Empty', empty_slot_slots_path, class: "btn btn-primary m-1" %>
  </li>
</ul>  

<div class="row">
  <% @slot.each do |slot| %>
    <div class="col-sm-4 m-2">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><p><strong>Slot Number: </strong><%= slot.slot_number%></p></h5>
            <p><strong>Slot Id: </strong><%= slot.id%></p>
            <p><strong>Floor Id: </strong><%= slot.floor_id%></p>
            
            <% if slot.status && slot.customer_detail.confirm.nil? %>
              <p><strong>Booking Status: </strong><%= "Not Available"%></p>
            <% elsif slot.status %> 
              <p><strong>Booking Status: </strong><%= "Booked"%></p> 
            <%else%>
              <p><strong>Booking Status: </strong><%= "Empty"%></p>   
            <%end%>

            <%= link_to '', slot_path(slot), class: "btn btn-info fa-solid fa-eye" %>
            <%= link_to '', slot_path(slot),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger fa-solid fa-trash" %>
            <%= link_to '', edit_slot_path(slot), class: "btn btn-primary fa-solid fa-pen-to-square" %> 
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= link_to 'back', root_path, class: "btn btn-primary m-1"%>

app/views/slots/booked_slot.html.erb
<%= render "show_slots"%>

app/views/slots/edit.html.erb
<div class="card text-white bg-secondary mb-3" style="max-width: auto">
  <% if @slot.errors.any? %>
  <h2>The following errors prevented the slot from being saved</h2>
  <ul>
    <% @slot.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <div class= "col-lg-6 mx-lg-auto" style="margin: 50px; >
    <div class="card shadow">
      <div class="card-header bg-striped text-white">
        <h2 class="card-title" >Edit Slot</h2>
      </div>
      <div class="card-body bg-info text-white">
        <%= form_with(model: @slot, local: true) do |f| %>
          <p> 
            <%= f.label :slot_number, class: 'mb-2'    %><br/> 
            <%= f.number_field :slot_number ,Placeholder: "Enter Slot", class: "form-control form-control-lg"  %>
          </p>

          <p>
          <%= f.submit 'submit', class: "btn btn-primary" %> 
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>  

app/views/slots/empty_slot.html.erb
<%= render "show_slots"%>

app/views/slots/index.html.erb
<div class="row">
  <% @slot.each do |slot| %>
    <div class="col-sm-4 m-2">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><p><strong>Slot Number: </strong><%= slot.slot_number%></p></h5>
            <p><strong>Slot Id: </strong><%= slot.id%></p>
            <p><strong>Floor Id: </strong><%= slot.floor_id%></p>
            
            <% if slot.status && slot.customer_detail.confirm.nil? %>
              <p><strong>Booking Status: </strong><%= "Not Available"%></p>
            <% elsif slot.status %> 
              <p><strong>Booking Status: </strong><%= "Booked"%></p> 
            <%else%>
              <p><strong>Booking Status: </strong><%= "Empty"%></p>   
            <%end%>

            <%= link_to '', slot_path(slot), class: "btn btn-info fa-solid fa-eye" %>
            <%= link_to '', slot_path(slot),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger fa-solid fa-trash" %>
            <%= link_to '', edit_slot_path(slot), class: "btn btn-primary fa-solid fa-pen-to-square" %> 
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= link_to 'back', root_path, class: "btn btn-primary m-1"%>

app/views/slots/new.html.erb
<% if @slot.errors.any? %>
    <h2>The following errors prevented the SLOT from being saved</h2>
    <ul>
    <% @slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %> 

<div class="card text-white bg-secondary mb-3" style="max-width: auto">
<div class= "col-lg-6 mx-lg-auto" style="margin: 50px; >
  <div class="card shadow">
    <div class="card-header bg-striped text-white">
      <h2 class="card-title" >Add Slots</h2>
    </div>
    <div class="card-body bg-info text-white">
  <%= form_with scope: :slot, url: slots_path, local: true do |f| %>
    <p> 
        <%= f.label :slot_number, class: 'mb-2'   %><br/>
        <%= f.number_field :slot_number, Placeholder: "Enter Slot Number", class: "form-control form-control-lg" %>
    </p>
    <p> 
        <%= f.label :floor_id , class: 'mb-2'  %><br/>
        <%= f.number_field :floor_id, value: params[:id], class: "form-control form-control-lg" %>
    </p> 

    <p>
        <%= f.submit 'submit', class: "btn btn-primary" %> 
    </p>
<% end %>

   </div>
  </div>
</div>
</div>  

app/views/slots/show.html.erb
<div class= "col-lg-6 mx-lg-auto">
  <div class="card shadow">
    <div class="card-header">
    <h2 class="card-title">Slot Details</h2>
    </div>
    <div class="card-body">
      <p><strong>Slot Number: </strong><%= @slot.slot_number%></p>
      <p><strong>Slot id: </strong><%= @slot.id%></p>
      <p><strong>floor id: </strong><%= @slot.floor_id%></p>
      <p><strong>Booking Status: </strong><%= @slot.status%></p>
    </div>
  </div>
</div>


<%
=begin%>
 
    <%count=0%>
    <% @slot.user_detail.each do |t| %>
        <%count+=1%>
        
        <%="this slots has #{count} booked"%><p>
    <%end%>
    <%=count%>  
<%
=end%>