config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'customer_details/new/:id', to: 'customer_details#new', as: 'new_customer_details'
  get 'customer_details/:id/download', to: 'customer_details#download', as: 'download'
  get 'homes/hello'
  get 'homes/cpm'
  root to: 'homes#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'slots/new/:id', to: 'slots#new', as: 'new_slot'
  
  resources :slots do
    collection do
      get 'booked_slot', to: 'slots#booked_slot'
      get 'empty_slot', to: 'slots#empty_slot'
    end

    # member do
    #   get 'new/:id', to: 'slots#new', as: 'new_slot'
    # end
  end

  resources :customer_details, except: %i[new]

  resources :floors do
  end
  get 'floors/booked_floor/:id' => 'floors#booked_floor', as: 'booked_floor_slots'
  get 'floors/empty_floor/:id' => 'floors#empty_floor', as: 'empty_floor_slots'

end

app/models/floor.rb
# frozen_string_literal: true

class Floor < ApplicationRecord
  has_many :slots
  validates :number_of_floor, numericality: { only_integer: true, in: 0..10 }, uniqueness: true, presence: true
end

app/controllers/floors_controller.rb
# frozen_string_literal: true

class FloorsController < ApplicationController
  before_action :check_user, only: %i[new edit update destroy]
  before_action :set_floor, only: %i[edit update destroy show]

  def new
    @floor = Floor.new
  end

  def index
    @floor = Floor.all
  end

  def show
    @floor = @floor.slots
  end

  def edit; end

  def update
    if @floor.update(floor_params)
      flash[:notice] = 'Floor changed'
      redirect_to @floor
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @floor = Floor.new(floor_params)
    if @floor.save
      flash[:notice] = 'Floor successfully created'
      redirect_to floors_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    if @floor.destroy
      flash[:notice] = 'Floor successfully deleted'
    else
      flash[:alert] = 'Failed to delete floor'
    end
    redirect_to floors_path
  end

  private

  def floor_params
    params.require(:floor).permit(:number_of_floor)
  end

  def set_floor
    @floor = Floor.find_by(id: params[:id])
    unless @floor
      flash[:alert] = 'Floor not found'
      redirect_to floors_path
    end
  end
end

app/helpers/floors_helper.rb
# frozen_string_literal: true

module FloorsHelper
end

app/views/floors/_form.html.erb
<%= form_with scope: :floor, url: floors_path, local: true do |f| %>
  <% if @floor.errors.any? %>
    <h2>The following errors prevented the user from being saved</h2>
    <ul>
        <% @floor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  <% end %> 
  <p> 
    <%= f.label :number_of_floor, class: 'mb-2'    %><br/> 
    <%= f.number_field :number_of_floor,Placeholder: "enter floor", class: "form-control form-control-lg"  %>
  </p> 

  <p>
    <%= f.submit 'submit', class: "btn btn-primary" %> 
  </p>
<% end %>

app/views/floors/_slot.html.erb
<h3> All Slots</h3>  

  <ul class="nav justify-content-center">
    <% if current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'All', floor_path, class: "btn btn-primary m-1" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Booked', booked_floor_slots_path, class: "btn btn-primary m-1" %>
        </li>
    <% else %>
        <li class="nav-item">
          <%= link_to 'Available For Booking', empty_floor_slots_path, class: "btn btn-primary m-1" %>
        </li>
    <% end %>
  </ul>  

<div class="row text-bg-light " style="width: auto; " >
  <% @floor.each do |slot| %>
    <div class="card" style="margin: 2px;" >
      <div  class="card-header"><strong>Slot Number: </strong><%= slot.slot_number%></div>
      <div class="card-body"> 
        <% if slot.status && slot.customer_detail.confirm.nil? %>
          <p><strong>Booking Status: </strong><%= "Not Available"%></p>
        <% elsif slot.status %> 
          <p><strong>Booking Status: </strong><%= "Booked"%></p> 
        <%else%>
          <p><strong>Booking Status: </strong><%= "Empty"%></p>
        <%end%>
        <% if current_user.admin%>
          <span class="dropdown">
            <a class=" dropdown-toggle btn btn-primary"  data-toggle="dropdown"  aria-expanded="false">
              Action
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <p class="dropdown-item"><i class="fa-solid fa-eye mr-2"></i><%= link_to 'show', slot_path(slot) %></p>
                <p class="dropdown-item"><i class="fa-solid fa-trash mr-2"></i><%= link_to 'delete', slot_path(slot),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                <p class="dropdown-item"><i class="fa-solid fa-pen-to-square mr-2"></i><%= link_to 'edit', edit_slot_path(slot) %>
            </div>
          </span> 
        <%end%>
        <span><%= link_to 'Apply', new_customer_details_path(slot.id), class: "btn btn-primary m-2"  %></span>
      </div>
    </div>
  <% end %>
</div>
<% if current_user.admin? %>
  <%= link_to 'Add Slot', new_slot_path(params[:id]), class: "btn btn-primary m-3"  %>
<%end%>

app/views/floors/booked_floor.html.erb
<%= render "slot" %>

app/views/floors/edit.html.erb
<h2>edit floor</h2>
<% if @floor.errors.any? %>
  <h2>The following errors prevented the floor from being saved</h2>
  <ul>
    <% @floor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="card text-white bg-secondary mb-3" style="max-width: auto">
  <div class= "col-lg-6 mx-lg-auto" style="margin: 50px; >
    <div class="card shadow">
      <div class="card-header bg-striped text-white">
        <h2 class="card-title" >Edit Floor</h2>
      </div>
      <div class="card-body bg-info text-white">
        <%= form_with(model: @floor, local: true) do |f| %>
          <p> 
            <%= f.label :number_of_floor, class: 'mb-2'    %><br/> 
            <%= f.number_field :number_of_floor,Placeholder: "Enter Name", class: "form-control form-control-lg"  %>
          </p>

          <p>
        <%= f.submit 'submit', class: "btn btn-primary" %> 
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>  

app/views/floors/empty_floor.html.erb
<%= render "slot"%>

app/views/floors/index.html.erb
<h3> All Floors </h3>

<div class="row text-bg-light " style="max-width: auto ">
  <% @floor.each do |floor| %>  
    <div class="card m-3"  >
      <div  class="card-header"><strong>Floor Number: </strong><%= floor.number_of_floor %></div>
      <div class="card-body">
        <%= "This floor has #{floor.slots.count} slots"%>
        <%if !current_user.admin %>
          <%= link_to 'Click', empty_floor_slots_path(floor), class: "btn btn-primary" %>
        <% else %>
          <%= link_to 'Click', floor_path(floor), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>  
<%= link_to 'back', root_path, class: "btn btn-primary"%>
<% if current_user.admin%>

<%= link_to 'Add Floor', new_floor_path, class: "btn btn-primary" %>
<%end%>



 



<%
=begin%>
 
 <p><strong>Floor Id: </strong><%= floor.id %></p> 
         <td><%= link_to 'Edit', edit_floor_path(floor)%></td>   
<%
=end%>


<%
=begin%>
 <% @user_detail.floor.each do |car|%>
            <li> <%= link_to 'apply for booking', new_user_detail_path(car)%> </li>
            <%end%> 
<%
=end%>





          <%
=begin%>
 <td><%= link_to 'Edit', edit_floor_path(floor) %></td>   
<%
=end%>
    

<%
=begin%>

<ul>
# <li><%= link_to 'create floor', new_floor_path %></li>
</ul>
 

  <td><%= link_to 'Delete', floor_path(floor),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
          <td><%= link_to 'Edit', edit_floor_path(floor) %></td>  
<%
=end%>

app/views/floors/new.html.erb
<div class="card text-white bg-secondary mb-3" style="max-width: auto">
  <div class= "col-lg-6 mx-lg-auto" style="margin: 50px; >
    <div class="card shadow">
      <div class="card-header bg-striped text-white">
        <h2 class="card-title" >Add Floor</h2>
      </div>
      <div class="card-body bg-info text-white">
        <%= render "form"%>
      </div>
    </div>
  </div>
</div>  

app/views/floors/show.html.erb
<h3> All Slots</h3>  
<%= render "slot"%>

  <%
=begin%>
 <ul class="nav justify-content-center">
    <li class="nav-item">
      <%= link_to 'All', "#", class: "btn btn-primary m-1" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Booked', "#", class: "btn btn-primary m-1" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Empty', "#", class: "btn btn-primary m-1" %>
    </li>
  </ul>  
<%
=end%>