config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'customer_details/new/:id', to: 'customer_details#new', as: 'new_customer_details'
  get 'customer_details/:id/download', to: 'customer_details#download', as: 'download'
  get 'homes/hello'
  get 'homes/cpm'
  root to: 'homes#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'slots/new/:id', to: 'slots#new', as: 'new_slot'
  
  resources :slots do
    collection do
      get 'booked_slot', to: 'slots#booked_slot'
      get 'empty_slot', to: 'slots#empty_slot'
    end

    # member do
    #   get 'new/:id', to: 'slots#new', as: 'new_slot'
    # end
  end

  resources :customer_details, except: %i[new]

  resources :floors do
  end
  get 'floors/booked_floor/:id' => 'floors#booked_floor', as: 'booked_floor_slots'
  get 'floors/empty_floor/:id' => 'floors#empty_floor', as: 'empty_floor_slots'

end

app/models/customer_detail.rb
# frozen_string_literal: true

# usermodel
require 'csv'

class CustomerDetail < ApplicationRecord
  belongs_to :slot
  belongs_to :user
  
  before_create do 
    self.car_color = car_color.downcase.titleize
    self.car_number = car_number.upcase
  end

  validates :name, :car_color, presence: true, length: { maximum: 30 }

  validates :in_time, presence: true

  validates_comparison_of :in_time, greater_than_or_equal_to: Time.now.strftime('%d/%m/%Y %H:%M')

  validates :out_time, comparison: { greater_than: :in_time }, presence: true

  validates :car_number, uniqueness: true, presence: true,
                         format: { with: /\A([A-Z]{2})+[0-9]{2}+[A-Z]{2}+[0-9]{4}\z/i }


  def to_csv(current_user)
    # @email = current_user.email
      column_names = %w[name car_color email in_time out_time car_number]
      CSV.generate do |csv|
        csv << column_names
        # csv << attributes.values_at(*column_names)

        row = attributes.values_at(*column_names)
        row[column_names.index('email')] = current_user.email
        csv << row
      end
  end
end

app/controllers/customer_details_controller.rb
# frozen_string_literal: true

# customer controller  
class CustomerDetailsController < ApplicationController
  before_action :check_user, only: %i[destroy edit]
  before_action :set_ud, only: %i[edit update show destroy]

  def new
    @ud = Slot.find_by(id: params[:id])
    if @ud&.status
      flash[:notice] = 'Already Booked'
      redirect_to floor_path
    else
      @ud = CustomerDetail.new
    end
  end

  def index
    @ud = CustomerDetail.all
  end

  def show; end

  def edit; end

  def create
    @ud = CustomerDetail.new(ud_params)
    if CustomerDetails::CreateCustomerDetailService.new(@ud, current_user).call
      flash[:notice] = 'Successfully applied. Please Check Your Mail'
      redirect_to @ud
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @ud.update(ud_params)
      UserDetailMailer.booking_confirmation(@ud, @ud, 'cust').deliver_later
      flash[:notice] = 'Details Updated'
      redirect_to customer_details_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if CustomerDetails::DestroyCustomerDetailService.new(@ud).call
      flash[:notice] = 'Customer detail successfully deleted'
      redirect_to customer_details_path
    else
      flash[:alert] = 'Failed to delete customer detail'
      redirect_to customer_details_path
    end
  end

  def download
    @ud = CustomerDetail.find(params[:id])
    respond_to do |format|
      format.csv { send_data @ud.to_csv(current_user), filename: "#{@ud.name}-#{Date.today}.csv" }
    end
  end

  private

  def ud_params
    params.require(:customer_detail).permit(:name, :car_color, :car_number, :in_time, :out_time, :slot_id, :confirm, :user_id)
  end

  def set_ud
    @ud = CustomerDetail.find_by(id: params[:id])
    unless @ud
      flash[:alert] = 'Customer detail not found'
      redirect_to customer_details_path
    end
  end
end

app/views/customer_details/_form.html.erb
          <% if @ud.errors.any? %>
            <h2>The following errors prevented the user from being saved</h2>
            <% @ud.errors.full_messages.each do |msg| %>
              <p><%= msg %></p>
            <% end %>
          <% end %> 
          
        <%= form_with scope: :customer_detail, url: customer_details_path, local: true do |f| %>
          
          <p> 
            <%= f.hidden_field :id, value: params[:id]%>
            <%= f.label :name, class: 'mb-2'  %>
            <%= f.text_field :name,Placeholder: "Enter Vailed name", value: current_user.name , class: "form-control form-control-lg" %>
          </p>

          <p> 
            <%= f.label :car_number, class: 'mb-2'  %>
            <%= f.text_field :car_number,Placeholder: "Enter car number", autofocus: true, class: "form-control form-control-lg" %>
          </p>

          <p> 
            <%= f.label :car_color, class: 'mb-2'  %>
            <%= f.text_field :car_color,Placeholder: "Enter car color", autofocus: true, class: "form-control form-control-lg" %>
          </p>

          <p> 
            <%= f.label :in_time, class: 'mb-2'  %>
            <%= f.datetime_field :in_time, Placeholder: "Enter time", autofocus: true, class: "form-control form-control-lg"%>
          </p>

          <p> 
            <%= f.label :out_time, class: 'mb-2'  %>
            <%= f.datetime_field :out_time,Placeholder: "Enter time", autofocus: true, class: "form-control form-control-lg"%>
          </p>

          <p> 
              <%= f.hidden_field :slot_id ,value: params[:id] %>
          </p>

          <p> 
              <%= f.hidden_field :user_id ,value: current_user.id %>
          </p>
          
          <p>
            <%= f.submit 'submit', class: "btn btn-primary" %> 
          </p>
          
        <% end %>

app/views/customer_details/edit.html.erb
<div class="card text-white bg-secondary mb-3" style="max-width: auto">
  <div class= "col-lg-6 mx-lg-auto" style="margin: 50px; >
    <div class="card shadow">
      <div class="card-header bg-striped text-white">
        <% if @ud.confirm.nil?%>
          <h2 class="card-title">Pending Request</h2>
        <% else%>
          <h2 class="card-title">Edit Details</h2>
        <%end%>    </div>
      <div class="card-body bg-info text-white">

        <% if @ud.errors.any? %>
          <h2>The following errors prevented the user from being saved</h2>
          <ul>
            <% @ud.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with(model: @ud, local: true) do |f| %>

          <% if @ud.confirm.nil?%>
            <p> 
              <%= f.hidden_field :confirm, value: "approved" %>
              <%f.hidden_field :user_id, value: params[:id]%>
            </p>

            <p>
              <%= f.submit 'Confirm', class: "btn btn-primary"%>
            </p>
            
          <%else%>

          <p> 
            <%= f.label :name, class: 'mb-2'  %>
            <%= f.text_field :name,Placeholder: "Enter name", autofocus: true, class: "form-control form-control-lg" %>
          </p>
          
          <p> 
            <%= f.label :car_number, class: 'mb-2'  %>
            <%= f.text_field :car_number,Placeholder: "Enter car number", autofocus: true, class: "form-control form-control-lg" %>
          </p>

          <p> 
            <%= f.label :car_color, class: 'mb-2'  %>
            <%= f.text_field :car_color,Placeholder: "Enter car color", autofocus: true, class: "form-control form-control-lg" %>
          </p>

          <p> 
            <%= f.label :in_time, class: 'mb-2'  %>
            <%= f.datetime_field :in_time,Placeholder: "Enter in time", autofocus: true, class: "form-control form-control-lg"%>
          </p>

          <p> 
            <%= f.label :out_time, class: 'mb-2'  %>
            <%= f.datetime_field :out_time,Placeholder: "Enter out time", autofocus: true, class: "form-control form-control-lg" %>
          </p>

          <p> 
            <%= f.label :slot_id, class: 'mb-2' %>  
            <%= f.number_field :slot_id , class: "form-control form-control-lg"%>
          </p> 

          <p> 
            <%= f.label :confirm, class: 'mb-2'  %>
            <%= f.text_field :confirm, Placeholder: "Enter Comment ", autofocus: true, class: "form-control form-control-lg"%>
          </p>
          

          <p>
            <%= f.submit 'submit', class: "btn btn-primary"%>
          </p>
          <%end%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customer_details/index.html.erb
<body>
<% if current_user.admin%>
  <h3>All Bookings</h3>
<% else %>
  <h3>Your Booking</h3>
<%end%>
  <table class="table table-success table-striped mr-4 ">
    <thead class="table-dark">
      </tr>
        <th>Name</th>
        <th>Email</th>
        <th>CarNumber</th>
        <th>CarColor</th>
        <th>SlotNumber</th>
        <th>Floor</th>
        <th>Status</th>
        <th colspan= "4">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @ud.each do |custo| %>
        <tr>
          <% if  current_user.admin || custo.user.email == current_user.email %>
            <td><%= custo.name %></td>
            <td><%= custo.user.email %></td>
            <td><%= custo.car_number %></td>
            <td><%= custo.car_color %></td>
            <td><%= custo.slot.slot_number%></td>
            <td><%= custo.slot.floor_id%></td>
            <td> <%= custo.confirm.nil? ? "Pending" : "Booked"%></td>
            <td><%= link_to '', customer_detail_path(custo), class: "btn btn-info fa-solid fa-eye" %></td>
            <td><%= link_to '', download_path(custo.id , format: 'csv'), class: " btn btn-info fa-regular fa-circle-down" %></td>

            <% if  current_user.admin %>
                <td><%= link_to '', customer_detail_path(custo),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger fa-solid fa-trash" %></td>
                <% if custo.confirm.nil?%>
                  <td><%= link_to 'PendingRequest', edit_customer_detail_path(custo.id), class: "btn btn-primary" %></td>
                <%else%>
                  <td><%= link_to '', edit_customer_detail_path(custo), class: "btn btn-primary fa-solid fa-pen-to-square" %></td>
                <%end%>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>




















<%
=begin%>
 <p>
     <button><%= link_to 'back', root_path %></button>

  <%= link_to 'Create new users ', new_user_path %></br>
  <%= link_to 'return to user prog', users_path %>
</p> 
<%
=end%>
   <%
=begin%>
 <td><%= user.floor_id %></td 
<%
=end%>

app/views/customer_details/new.html.erb
<div class="card text-white bg-secondary mb-3" style="max-width: auto">
  <div class= "col-lg-6 mx-lg-auto" style="margin: 50px; >
    <div class="card shadow">
      <div class="card-header bg-striped text-white">
        <h2 class="card-title" >Enter Details</h2>
      </div>  
      <div class="card-body bg-info text-white">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>  





    

app/views/customer_details/show.html.erb
<div class= "col-lg-6 mx-lg-auto">
  <div class="card shadow">
    <div class="card-header">
    <h2 class="card-title">Your Details</h2>
    </div>
    <div class="card-body">
      <p><strong>Name: </strong><%= @ud.name %></p>
      <p><strong>Car Number: </strong><%= @ud.car_number %></p>
      <p><strong>Car Color: </strong><%= @ud.car_color %></p>
      <p><strong>In Time: </strong><%= @ud.in_time.strftime('%d/%m/%Y %H:%M') %></p>
      <p><strong>Out Time: </strong><%= @ud.out_time.strftime('%d/%m/%Y %H:%M') %></p>
      <p><strong>Slot Id: </strong><%= @ud.slot_id%></p>
      <p><strong>Slot Number: </strong><%= @ud.slot.slot_number%></p>
      <p><strong>Floor : </strong><%= @ud.slot.floor_id%></p>
      <%if @ud.confirm.nil? %>
        <p><strong>Status : </strong><%= "Pending"%><p>
      <%else%>   
        <p><strong>Status : </strong><%= "Booked"%><p>
      <%end%>
      <% m= @ud.out_time %>
      <% n= @ud.in_time %>
      <strong>Bill Amount: <strong><%= (((m-n)/1.hours).round)*100%>
    </div>
  </div>
</div>

<%
=begin%>
<button><%= link_to "back", new_user_registration_path %></button>

 <%= @ud.floor.number_of_floor if @ud.floor %>
 <%= link_to 'Delete', user_detail_path,data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<%= link_to 'return to userdetail', user_details_path %> 
<%= @ud.floor.number_of_floor if @ud.floor %> 
<%
=end%>